# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Poketmon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='capture',
            name='poketmon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='go.Poketmon'),
        ),
        migrations.AddField(
            model_name='capture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='go.User'),
        ),
    ]
